Spring:
  Application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kmrjiang/Springcloud.git
          label: master   #读取分支
server:
  port: 8888
